# For GetHistoricalCandles (Java client) and StreamHistoricalCandles
datafye-ohlc-historical.client.gbpoc.connectionDescriptor=solace://172.33.6.49:55555&client_name=gbpoc-ohlc-historical-client
datafye-ohlc-historical.client.gbpoc.responseTimeout=5
# For StreamHistoricalCandles
datafye-ohlc-historical.stream.gbpoc.trace=config

# For GetLiveCandles
datafye-ohlc-live-1.client.gbpoc.connectionDescriptor=solace://172.32.6.188:55555&client_name=gbpoc-ohlc-live-client
datafye-ohlc-live-1.client.gbpoc.responseTimeout=5

# For GetHistoricalCandles (REST client) and GetLiveCandles (REST client)
gb-poc.datafye.ohlc.apiep=172.32.138.108:7778

# For GetLiveTopOfBook (Java client) and StreamLiveTopOfBook
datafye-polygon-quote.client.gbpoc.connectionDescriptor=solace://172.33.6.49:55555&client_name=gbpoc-quote-live-client
datafye-polygon-quote.client.gbpoc.responseTimeout=5
# For StreamLiveTopOfBook
datafye-polygon-quote.stream.gbpoc.trace=config
datafye-polygon-quote.stream.gbpoc.connectionDescriptor=ether://.&ifaddr=172.33.0.174&port=44443&server=false

# For GetLiveTopOfBook (REST client)
gb-poc.datafye.quote.apiep=172.32.138.108:7779

# For StreamLiveTrades
datafye-trade-live.client.gbpoc.connectionDescriptor=solace://172.33.6.49:55555&client_name=gbpoc-trade-live-client
datafye-trade-live.client.gbpoc.responseTimeout=5
datafye-trade-live.stream.gbpoc.trace=config
datafye-trade-live.stream.gbpoc.connectionDescriptor=ether://.&ifaddr=172.33.15.152&port=44443&server=false
